services:
  db:
    image: mysql:8.0
    container_name: recruitment-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: recruitment_db1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - recruitment-db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruitment-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DB_URL: jdbc:mysql://db:3306/recruitment_db1?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Bangkok
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: ThisIsASecretKeyForJwtAuthenticationMustBeAtLeast32BytesLong
      GOOGLE_CLIENT_ID: 278300133755-gaho7bghdckdquguts7kfh5j62jlh2t2.apps.googleusercontent.com
    ports:
      - "8080:8080"

volumes:
  recruitment-db-data:
