import type { Job } from "../types/job";

export const jobs: Job[] = [
  {
    id: "job_003",
    title: "UI/UX Designer",
    category: "Design",
    department: "Product",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 12000000, max: 18000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Figma", "Adobe XD", "User Research"],
    description: [
      "Design user-friendly interfaces for web and mobile platforms.",
      "Collaborate closely with developers and product teams to translate business requirements into intuitive UI/UX.",
      "Create wireframes, prototypes, and high-fidelity mockups.",
    ],
    requirements: [
      "2+ years experience in UI/UX Design.",
      "A strong portfolio showcasing web and mobile design projects.",
      "Proficient in Figma, Adobe XD, or similar design tools.",
      "Good understanding of user-centered design principles.",
    ],
    benefits: [
      "Creative and open working environment.",
      "Flexible working hours.",
      "Annual performance review and 13th-month salary.",
    ],
    company: {
      name: "Tiki Corporation",
      address: "District 1, Ho Chi Minh City",
      bio: "Tiki is one of the most trusted e-commerce platforms in Vietnam, offering millions of products across various categories.",
    },
    workingHours: "Mon - Fri (9:00 AM - 6:00 PM)",
    deadline: "2026-05-10",
  },
  {
    id: "job_004",
    title: "Digital Marketing Specialist",
    category: "Marketing",
    department: "Marketing",
    jobType: "Full-time",
    experienceLevel: "1+ year",
    isBookmarked: true,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 10000000, max: 16000000, currency: "VND" },
    location: "Da Nang",
    postedAt: "5 days ago",
    skills: ["SEO", "Google Ads", "Content Marketing"],
    description: [
      "Manage digital marketing campaigns across Google, Facebook, and other platforms.",
      "Analyze marketing performance metrics to optimize ROI.",
      "Create and manage content for social media channels.",
    ],
    requirements: [
      "Experience in digital marketing, specifically SEO/SEM and social media advertising.",
      "Analytical mindset with the ability to interpret performance data.",
      "Creative thinking and excellent communication skills.",
    ],
    benefits: [
      "Bonus KPI based on campaign performance.",
      "Remote work options available.",
      "Health insurance and annual company trip.",
    ],
    company: {
      name: "Shopee Vietnam",
      address: "Hai Chau, Da Nang",
      bio: "Shopee is the leading e-commerce platform in Southeast Asia and Taiwan.",
    },
    workingHours: "Mon - Fri (8:30 AM - 5:30 PM)",
    deadline: "2026-05-05",
  },
  {
    id: "job_005",
    title: "Data Analyst",
    category: "Data",
    department: "Data Science",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 15000000, max: 22000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "1 week ago",
    skills: ["SQL", "Python", "Power BI"],
    description: [
      "Analyze large datasets to identify trends and insights.",
      "Build dynamic dashboards for business intelligence.",
      "Collaborate with stakeholders to understand data needs.",
    ],
    requirements: [
      "Strong proficiency in SQL and Python.",
      "Experience with data visualization tools like Power BI or Tableau.",
      "Strong analytical thinking and problem-solving skills.",
    ],
    benefits: [
      "Premium health insurance.",
      "Budget for professional training and certification.",
      "Free lunch and modern office space.",
    ],
    company: {
      name: "VNG Corporation",
      address: "District 7, HCMC",
      bio: "VNG is the leading tech company in Vietnam with millions of active users across gaming, communication, and digital content.",
    },
    workingHours: "Mon - Fri (8:30 AM - 5:30 PM)",
    deadline: "2026-05-15",
  },
  {
    id: "job_006",
    title: "HR Executive",
    category: "Human Resources",
    department: "HR",
    jobType: "Full-time",
    experienceLevel: "1+ year",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 9000000, max: 14000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "4 days ago",
    skills: ["Recruitment", "Communication", "Onboarding"],
    description: [
      "Manage end-to-end recruitment process.",
      "Organize employee engagement activities and team building.",
      "Handle employee onboarding and offboarding procedures.",
    ],
    requirements: [
      "Minimum 1 year of experience in HR or recruitment.",
      "Excellent communication and interpersonal skills.",
      "Detail-oriented and highly organized.",
    ],
    benefits: [
      "Annual team-building trip.",
      "Year-end bonus and performance rewards.",
    ],
    company: {
      name: "Viettel Group",
      address: "Ba Dinh, Ha Noi",
      bio: "Viettel is a Vietnamese multinational telecommunications company.",
    },
    workingHours: "Mon - Fri (8:00 AM - 5:00 PM)",
    deadline: "2026-05-08",
  },
  {
    id: "job_007",
    title: "Mobile Developer (Flutter)",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: true,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 18000000, max: 26000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "3 days ago",
    skills: ["Flutter", "Dart", "Firebase", "REST API"],
    description: [
      "Develop and maintain high-quality mobile applications using Flutter.",
      "Integrate with backend services via RESTful APIs.",
      "Ensure application performance, quality, and responsiveness.",
    ],
    requirements: [
      "2+ years of professional experience with Flutter and Dart.",
      "Experience with state management solutions (Provider, Bloc, etc.).",
      "Familiarity with native Android or iOS development is a plus.",
    ],
    benefits: [
      "13th-month salary and bi-annual review.",
      "Hybrid working model.",
      "MacBook provided.",
    ],
    company: {
      name: "MoMo",
      address: "District 1, HCMC",
      bio: "MoMo is Vietnam's leading e-wallet and mobile payment app.",
    },
    workingHours: "Mon - Fri (9:00 AM - 6:00 PM)",
    deadline: "2026-05-12",
  },
  {
    id: "job_008",
    title: "Accountant",
    category: "Finance",
    department: "Accounting",
    jobType: "Full-time",
    experienceLevel: "1+ year",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 10000000, max: 15000000, currency: "VND" },
    location: "Binh Duong",
    postedAt: "6 days ago",
    skills: ["Accounting", "Excel", "MISA"],
    description: [
      "Manage daily financial transactions and records.",
      "Prepare monthly, quarterly, and annual financial reports.",
      "Ensure compliance with accounting principles and regulations.",
    ],
    requirements: [
      "Degree in Accounting, Finance, or related field.",
      "Proficient in Microsoft Excel and accounting software (e.g., MISA).",
      "High attention to detail and accuracy.",
    ],
    benefits: [
      "Comprehensive health insurance.",
      "Annual leave of 14 days.",
    ],
    company: {
      name: "Vinamilk",
      address: "Thu Dau Mot, Binh Duong",
      bio: "Vinamilk is the largest dairy company in Vietnam.",
    },
    workingHours: "Mon - Fri (8:00 AM - 5:00 PM)",
    deadline: "2026-05-20",
  },
  {
    id: "job_009",
    title: "Sales Executive",
    category: "Sales",
    department: "Sales",
    jobType: "Full-time",
    experienceLevel: "Entry level",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 8000000, max: 20000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Communication", "Negotiation", "B2B Sales"],
    description: [
      "Identify and develop new business opportunities.",
      "Maintain and build strong relationships with clients.",
      "Achieve monthly and quarterly sales targets.",
    ],
    requirements: [
      "Previous experience in sales or customer service is preferred.",
      "Excellent communication and negotiation skills.",
      "Self-motivated and result-oriented.",
    ],
    benefits: [
      "High commission rate based on sales.",
      "Transportation allowance.",
    ],
    company: {
      name: "PNJ",
      address: "Phu Nhuan, HCMC",
      bio: "Phu Nhuan Jewelry is a leading jewelry manufacturer and retailer in Asia.",
    },
    workingHours: "Mon - Sat (8:30 AM - 5:30 PM)",
    deadline: "2026-05-18",
  },
  {
    id: "job_010",
    title: "QA Tester",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 12000000, max: 18000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "1 day ago",
    skills: ["Testing", "Automation", "Selenium", "Jira"],
    description: [
      "Perform manual and automated testing of software applications.",
      "Design and create test cases, test plans, and test scripts.",
      "Report and track bugs using Jira or similar tools.",
    ],
    requirements: [
      "Experience in software quality assurance.",
      "Familiarity with automation tools like Selenium or Cypress is a plus.",
      "Detail-oriented with strong problem-solving skills.",
    ],
    benefits: [
      "Access to continuous learning and training programs.",
      "Friendly and supportive team culture.",
    ],
    company: {
      name: "CMC Corporation",
      address: "Cau Giay, Ha Noi",
      bio: "CMC is one of the leading ICT groups in Vietnam.",
    },
    workingHours: "Mon - Fri (8:30 AM - 5:30 PM)",
    deadline: "2026-05-22",
  },
  {
    id: "job_011",
    title: "Business Analyst",
    category: "Software Development",
    department: "Product",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 16000000, max: 24000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "3 days ago",
    skills: ["Analysis", "Documentation", "Agile/Scrum"],
    description: [
      "Gather and analyze business requirements from stakeholders.",
      "Create detailed documentation including use cases and user stories.",
      "Act as a bridge between the business team and the development team.",
    ],
    requirements: [
      "3+ years of experience as an IT Business Analyst.",
      "Strong understanding of the software development lifecycle (Agile/Scrum).",
      "Excellent communication and presentation skills.",
    ],
    benefits: [
      "Performance bonus and project bonuses.",
      "Health insurance package for employees.",
    ],
    company: {
      name: "Techcombank",
      address: "District 1, HCMC",
      bio: "Techcombank is one of the leading commercial banks in Vietnam.",
    },
    workingHours: "Mon - Fri (8:00 AM - 5:00 PM)",
    deadline: "2026-05-25",
  },
  {
    id: "job_012",
    title: "Content Writer",
    category: "Marketing",
    department: "Marketing",
    jobType: "Contract",
    experienceLevel: "Entry level",
    isBookmarked: false,
    logo: "https://via.placeholder.com/100?text=Logo",
    salary: { min: 8000000, max: 12000000, currency: "VND" },
    location: "Remote",
    postedAt: "2 days ago",
    skills: ["Writing", "SEO", "Copywriting"],
    description: [
      "Write engaging blog posts, articles, and marketing copy.",
      "Optimize content for SEO to improve search rankings.",
      "Collaborate with the design team to create visual content.",
    ],
    requirements: [
      "Excellent writing and editing skills in Vietnamese and English.",
      "Basic understanding of SEO best practices.",
      "Creative mindset with the ability to research various topics.",
    ],
    benefits: [
      "100% remote work.",
      "Flexible working schedule.",
    ],
    company: {
      name: "TopCV Vietnam",
      address: "Online",
      bio: "TopCV is the leading HR Tech company in Vietnam, connecting millions of candidates with employers.",
    },
    workingHours: "Flexible",
    deadline: "2026-05-30",
  },
];