export const jobs: Job[] = [
  {
    id: "job_003",
    title: "UI/UX Designer",
    category: "Design",
    salary: { min: 12000000, max: 18000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Figma", "Adobe XD", "User Research"],
    description: [
      "Design user-friendly interfaces for web/mobile.",
      "Collaborate with developers and product team.",
    ],
    requirements: [
      "2+ years experience in UI/UX.",
      "Portfolio required.",
    ],
    benefits: [
      "Creative environment.",
      "Flexible hours.",
    ],
    company: {
      name: "Tiki Corporation",
      address: "District 1, Ho Chi Minh City",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-10",
  },

  {
    id: "job_004",
    title: "Digital Marketing Specialist",
    category: "Marketing",
    salary: { min: 10000000, max: 16000000, currency: "VND" },
    location: "Da Nang",
    postedAt: "5 days ago",
    skills: ["SEO", "Google Ads", "Content Marketing"],
    description: [
      "Manage digital campaigns.",
      "Analyze marketing performance.",
    ],
    requirements: [
      "Experience in digital marketing.",
      "Analytical mindset.",
    ],
    benefits: ["Bonus KPI", "Remote option"],
    company: {
      name: "Shopee Vietnam",
      address: "Hai Chau, Da Nang",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-05",
  },

  {
    id: "job_005",
    title: "Data Analyst",
    category: "Data",
    salary: { min: 15000000, max: 22000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "1 week ago",
    skills: ["SQL", "Python", "Power BI"],
    description: ["Analyze data trends.", "Build dashboards."],
    requirements: ["Strong SQL", "Analytical thinking"],
    benefits: ["Health insurance", "Training"],
    company: {
      name: "VNG Corporation",
      address: "District 7, HCMC",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-15",
  },

  {
    id: "job_006",
    title: "HR Executive",
    category: "Human Resources",
    salary: { min: 9000000, max: 14000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "4 days ago",
    skills: ["Recruitment", "Communication"],
    description: ["Handle recruitment process."],
    requirements: ["1+ year HR experience"],
    benefits: ["Team building", "Bonus"],
    company: {
      name: "Viettel Group",
      address: "Ba Dinh, Ha Noi",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-08",
  },

  {
    id: "job_007",
    title: "Mobile Developer (Flutter)",
    category: "Software Development",
    salary: { min: 18000000, max: 26000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "3 days ago",
    skills: ["Flutter", "Dart"],
    description: ["Build mobile apps."],
    requirements: ["2+ years Flutter"],
    benefits: ["13th salary"],
    company: {
      name: "MoMo",
      address: "District 1, HCMC",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-12",
  },

  {
    id: "job_008",
    title: "Accountant",
    category: "Finance",
    salary: { min: 10000000, max: 15000000, currency: "VND" },
    location: "Binh Duong",
    postedAt: "6 days ago",
    skills: ["Accounting", "Excel"],
    description: ["Manage financial records."],
    requirements: ["Accounting degree"],
    benefits: ["Insurance"],
    company: {
      name: "Vinamilk",
      address: "Thu Dau Mot, Binh Duong",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-20",
  },

  {
    id: "job_009",
    title: "Sales Executive",
    category: "Sales",
    salary: { min: 8000000, max: 20000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Communication", "Negotiation"],
    description: ["Find and manage clients."],
    requirements: ["Sales experience"],
    benefits: ["Commission"],
    company: {
      name: "PNJ",
      address: "Phu Nhuan, HCMC",
    },
    workingHours: "Mon - Sat",
    deadline: "2026-05-18",
  },

  {
    id: "job_010",
    title: "QA Tester",
    category: "Software Development",
    salary: { min: 12000000, max: 18000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "1 day ago",
    skills: ["Testing", "Automation"],
    description: ["Test software quality."],
    requirements: ["QA experience"],
    benefits: ["Training"],
    company: {
      name: "CMC Corporation",
      address: "Cau Giay, Ha Noi",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-22",
  },

  {
    id: "job_011",
    title: "Business Analyst",
    category: "Software Development",
    salary: { min: 16000000, max: 24000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "3 days ago",
    skills: ["Analysis", "Documentation"],
    description: ["Analyze business requirements."],
    requirements: ["BA experience"],
    benefits: ["Bonus"],
    company: {
      name: "Techcombank",
      address: "District 1, HCMC",
    },
    workingHours: "Mon - Fri",
    deadline: "2026-05-25",
  },

  {
    id: "job_012",
    title: "Content Writer",
    category: "Marketing",
    salary: { min: 8000000, max: 12000000, currency: "VND" },
    location: "Remote",
    postedAt: "2 days ago",
    skills: ["Writing", "SEO"],
    description: ["Write blog & marketing content."],
    requirements: ["Good writing skills"],
    benefits: ["Remote work"],
    company: {
      name: "TopCV Vietnam",
      address: "Online",
    },
    workingHours: "Flexible",
    deadline: "2026-05-30",
  },
];