import type { Job } from "../types/job";

export const jobs: Job[] = [
  {
    id: "job_003",
    title: "UI/UX Designer",
    category: "Design",
    department: "Product",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://th.bing.com/th/id/OIP.NHbsr79gc98UG6g9OjMyjgHaE7?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    salary: { min: 12000000, max: 18000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Figma", "Adobe XD", "User Research"],
    description: [
      "Design user-friendly interfaces for web and mobile platforms.",
      "Collaborate closely with developers and product teams to translate business requirements into intuitive UI/UX.",
      "Create wireframes, prototypes, and high-fidelity mockups.",
    ],
    requirements: [
      "2+ years experience in UI/UX Design.",
      "A strong portfolio showcasing web and mobile design projects.",
      "Proficient in Figma, Adobe XD, or similar design tools.",
      "Good understanding of user-centered design principles.",
    ],
    benefits: [
      "Creative and open working environment.",
      "Flexible working hours.",
      "Annual performance review and 13th-month salary.",
    ],
    company: {
      name: "Tiki Corporation",
      address: "District 1, Ho Chi Minh City",
      bio: "Tiki is one of the most trusted e-commerce platforms in Vietnam, offering millions of products across various categories.",
    },
    workingHours: "Mon - Fri (9:00 AM - 6:00 PM)",
    deadline: "2026-05-10",
    createdBy: "company1",
    status: "approved",
  },
  {
    id: "job_004",
    title: "Digital Marketing Specialist",
    category: "Marketing",
    department: "Marketing",
    jobType: "Full-time",
    experienceLevel: "1+ year",
    isBookmarked: true,
    logo: "https://static.vecteezy.com/system/resources/previews/024/726/888/original/t-letter-t-logo-font-alphabet-design-and-icon-t-free-vector.jpg",
    salary: { min: 10000000, max: 16000000, currency: "VND" },
    location: "Da Nang",
    postedAt: "5 days ago",
    skills: ["SEO", "Google Ads", "Content Marketing"],
    description: [
      "Manage digital marketing campaigns across Google, Facebook, and other platforms.",
      "Analyze marketing performance metrics to optimize ROI.",
      "Create and manage content for social media channels.",
    ],
    requirements: [
      "Experience in digital marketing, specifically SEO/SEM and social media advertising.",
      "Analytical mindset with the ability to interpret performance data.",
      "Creative thinking and excellent communication skills.",
    ],
    benefits: [
      "Bonus KPI based on campaign performance.",
      "Remote work options available.",
      "Health insurance and annual company trip.",
    ],
    company: {
      name: "Shopee Vietnam",
      address: "Hai Chau, Da Nang",
      bio: "Shopee is the leading e-commerce platform in Southeast Asia and Taiwan.",
    },
    workingHours: "Mon - Fri (8:30 AM - 5:30 PM)",
    deadline: "2026-05-05",
    createdBy: "company2",
    status: "rejected",
  },
  {
    id: "job_005",
    title: "Data Analyst",
    category: "Data",
    department: "Data Science",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://graphicsfamily.com/wp-content/uploads/edd/2021/11/Free-Crypto-Financial-Letter-S-Logo-Design-Template-870x489.jpg",
    salary: { min: 15000000, max: 22000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "1 week ago",
    skills: ["SQL", "Python", "Power BI"],
    description: [
      "Analyze large datasets to identify trends and insights.",
      "Build dynamic dashboards for business intelligence.",
      "Collaborate with stakeholders to understand data needs.",
    ],
    requirements: [
      "Strong proficiency in SQL and Python.",
      "Experience with data visualization tools like Power BI or Tableau.",
      "Strong analytical thinking and problem-solving skills.",
    ],
    benefits: [
      "Premium health insurance.",
      "Budget for professional training and certification.",
      "Free lunch and modern office space.",
    ],
    company: {
      name: "VNG Corporation",
      address: "District 7, HCMC",
      bio: "VNG is the leading tech company in Vietnam with millions of active users across gaming, communication, and digital content.",
    },
    workingHours: "Mon - Fri (8:30 AM - 5:30 PM)",
    deadline: "2026-05-15",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_006",
    title: "HR Executive",
    category: "Human Resources",
    department: "HR",
    jobType: "Full-time",
    experienceLevel: "1+ year",
    isBookmarked: false,
    logo: "https://img.freepik.com/premium-vector/creative-logo-design-vector-illustration-tech-startup-company_1253202-57409.jpg",
    salary: { min: 9000000, max: 14000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "4 days ago",
    skills: ["Recruitment", "Communication", "Onboarding"],
    description: [
      "Manage end-to-end recruitment process.",
      "Organize employee engagement activities and team building.",
      "Handle employee onboarding and offboarding procedures.",
    ],
    requirements: [
      "Minimum 1 year of experience in HR or recruitment.",
      "Excellent communication and interpersonal skills.",
      "Detail-oriented and highly organized.",
    ],
    benefits: [
      "Annual team-building trip.",
      "Year-end bonus and performance rewards.",
    ],
    company: {
      name: "Viettel Group",
      address: "Ba Dinh, Ha Noi",
      bio: "Viettel is a Vietnamese multinational telecommunications company.",
    },
    workingHours: "Mon - Fri (8:00 AM - 5:00 PM)",
    deadline: "2026-05-08",
    createdBy: "company2",
    status: "approved",
  },
  {
    id: "job_007",
    title: "Mobile Developer (Flutter)",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: true,
    logo: "https://tse1.mm.bing.net/th/id/OIP.f8KMPuou7BgHN2HnIUbcSgHaF-?rs=1&pid=ImgDetMain&o=7&rm=3",
    salary: { min: 18000000, max: 26000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "3 days ago",
    skills: ["Flutter", "Dart", "Firebase", "REST API"],
    description: [
      "Develop and maintain high-quality mobile applications using Flutter.",
      "Integrate with backend services via RESTful APIs.",
      "Ensure application performance, quality, and responsiveness.",
    ],
    requirements: [
      "2+ years of professional experience with Flutter and Dart.",
      "Experience with state management solutions (Provider, Bloc, etc.).",
      "Familiarity with native Android or iOS development is a plus.",
    ],
    benefits: [
      "13th-month salary and bi-annual review.",
      "Hybrid working model.",
      "MacBook provided.",
    ],
    company: {
      name: "MoMo",
      address: "District 1, HCMC",
      bio: "MoMo is Vietnam's leading e-wallet and mobile payment app.",
    },
    workingHours: "Mon - Fri (9:00 AM - 6:00 PM)",
    deadline: "2026-05-12",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_008",
    title: "Accountant",
    category: "Finance",
    department: "Accounting",
    jobType: "Full-time",
    experienceLevel: "1+ year",
    isBookmarked: false,
    logo: "https://tse4.mm.bing.net/th/id/OIP.IM5T-uuabZODjPwGtWx7pAHaHa?w=626&h=626&rs=1&pid=ImgDetMain&o=7&rm=3",
    salary: { min: 10000000, max: 15000000, currency: "VND" },
    location: "Binh Duong",
    postedAt: "6 days ago",
    skills: ["Accounting", "Excel", "MISA"],
    description: [
      "Manage daily financial transactions and records.",
      "Prepare monthly, quarterly, and annual financial reports.",
      "Ensure compliance with accounting principles and regulations.",
    ],
    requirements: [
      "Degree in Accounting, Finance, or related field.",
      "Proficient in Microsoft Excel and accounting software (e.g., MISA).",
      "High attention to detail and accuracy.",
    ],
    benefits: [
      "Comprehensive health insurance.",
      "Annual leave of 14 days.",
    ],
    company: {
      name: "Vinamilk",
      address: "Thu Dau Mot, Binh Duong",
      bio: "Vinamilk is the largest dairy company in Vietnam.",
    },
    workingHours: "Mon - Fri (8:00 AM - 5:00 PM)",
    deadline: "2026-05-20",
    createdBy: "company2",
    status: "rejected",
  },
  {
    id: "job_009",
    title: "Sales Executive",
    category: "Sales",
    department: "Sales",
    jobType: "Full-time",
    experienceLevel: "Entry level",
    isBookmarked: false,
    logo: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/ce33f2102795941.5f3e946eb2e00.jpg",
    salary: { min: 8000000, max: 20000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Communication", "Negotiation", "B2B Sales"],
    description: [
      "Identify and develop new business opportunities.",
      "Maintain and build strong relationships with clients.",
      "Achieve monthly and quarterly sales targets.",
    ],
    requirements: [
      "Previous experience in sales or customer service is preferred.",
      "Excellent communication and negotiation skills.",
      "Self-motivated and result-oriented.",
    ],
    benefits: [
      "High commission rate based on sales.",
      "Transportation allowance.",
    ],
    company: {
      name: "PNJ",
      address: "Phu Nhuan, HCMC",
      bio: "Phu Nhuan Jewelry is a leading jewelry manufacturer and retailer in Asia.",
    },
    workingHours: "Mon - Sat (8:30 AM - 5:30 PM)",
    deadline: "2026-05-18",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_010",
    title: "QA Tester",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://tse4.mm.bing.net/th/id/OIP.4eopH6O1LeFYWRDEwYu7HQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    salary: { min: 12000000, max: 18000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "1 day ago",
    skills: ["Testing", "Automation", "Selenium", "Jira"],
    description: [
      "Perform manual and automated testing of software applications.",
      "Design and create test cases, test plans, and test scripts.",
      "Report and track bugs using Jira or similar tools.",
    ],
    requirements: [
      "Experience in software quality assurance.",
      "Familiarity with automation tools like Selenium or Cypress is a plus.",
      "Detail-oriented with strong problem-solving skills.",
    ],
    benefits: [
      "Access to continuous learning and training programs.",
      "Friendly and supportive team culture.",
    ],
    company: {
      name: "CMC Corporation",
      address: "Cau Giay, Ha Noi",
      bio: "CMC is one of the leading ICT groups in Vietnam.",
    },
    workingHours: "Mon - Fri (8:30 AM - 5:30 PM)",
    deadline: "2026-05-22",
    createdBy: "company2",
    status: "approved",
  },
  {
    id: "job_011",
    title: "Business Analyst",
    category: "Software Development",
    department: "Product",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: false,
    logo: "https://tse2.mm.bing.net/th/id/OIP.0OZiUtPdn3Kle3f1h-MkWwHaHa?w=740&h=740&rs=1&pid=ImgDetMain&o=7&rm=3",
    salary: { min: 16000000, max: 24000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "3 days ago",
    skills: ["Analysis", "Documentation", "Agile/Scrum"],
    description: [
      "Gather and analyze business requirements from stakeholders.",
      "Create detailed documentation including use cases and user stories.",
      "Act as a bridge between the business team and the development team.",
    ],
    requirements: [
      "3+ years of experience as an IT Business Analyst.",
      "Strong understanding of the software development lifecycle (Agile/Scrum).",
      "Excellent communication and presentation skills.",
    ],
    benefits: [
      "Performance bonus and project bonuses.",
      "Health insurance package for employees.",
    ],
    company: {
      name: "Techcombank",
      address: "District 1, HCMC",
      bio: "Techcombank is one of the leading commercial banks in Vietnam.",
    },
    workingHours: "Mon - Fri (8:00 AM - 5:00 PM)",
    deadline: "2026-05-25",
    createdBy: "company1",
    status: "rejected",
  },
  {
    id: "job_012",
    title: "Content Writer",
    category: "Marketing",
    department: "Marketing",
    jobType: "Contract",
    experienceLevel: "Entry level",
    isBookmarked: false,
    logo: "https://tse2.mm.bing.net/th/id/OIP.0OZiUtPdn3Kle3f1h-MkWwHaHa?w=740&h=740&rs=1&pid=ImgDetMain&o=7&rm=3",
    salary: { min: 8000000, max: 12000000, currency: "VND" },
    location: "Remote",
    postedAt: "2 days ago",
    skills: ["Writing", "SEO", "Copywriting"],
    description: [
      "Write engaging blog posts, articles, and marketing copy.",
      "Optimize content for SEO to improve search rankings.",
      "Collaborate with the design team to create visual content.",
    ],
    requirements: [
      "Excellent writing and editing skills in Vietnamese and English.",
      "Basic understanding of SEO best practices.",
      "Creative mindset with the ability to research various topics.",
    ],
    benefits: [
      "100% remote work.",
      "Flexible working schedule.",
    ],
    company: {
      name: "TopCV Vietnam",
      address: "Online",
      bio: "TopCV is the leading HR Tech company in Vietnam, connecting millions of candidates with employers.",
    },
    workingHours: "Flexible",
    deadline: "2026-05-30",
    createdBy: "company2",
    status: "pending",
  },
{
    id: "job_013",
    title: "Backend Developer (Node.js)",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 25000000, max: 40000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "1 day ago",
    skills: ["Node.js", "Express", "MongoDB", "Redis"],
    description: ["Build scalable microservices.", "Optimize database queries.", "Ensure system security."],
    requirements: ["3+ years with Node.js.", "Experience with cloud services (AWS)."],
    benefits: ["Unlimited PTO", "Stock options"],
    company: { name: "Grab Vietnam", address: "District 7, HCMC", bio: "Leading superapp." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-01",
    createdBy: "company1",
    status: "approved",
  },
  {
    id: "job_014",
    title: "Project Manager",
    category: "Management",
    department: "PMO",
    jobType: "Full-time",
    experienceLevel: "5+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 35000000, max: 60000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "2 days ago",
    skills: ["Agile", "Scrum", "Jira"],
    description: ["Manage project timelines.", "Bridge client and team."],
    requirements: ["PMP certification is a plus.", "Strong leadership."],
    benefits: ["Year-end bonus", "Health care"],
    company: { name: "FPT Software", address: "Cau Giay, Ha Noi", bio: "Global IT leader." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-05",
    createdBy: "company2",
    status: "approved",
  },
{
    id: "job_015",
    title: "DevOps Engineer",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 28000000, max: 42000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "3 days ago",
    skills: ["AWS", "Kubernetes", "CI/CD", "Terraform"],
    description: ["Manage cloud infrastructure.", "Automate deployment processes."],
    requirements: ["Expertise in AWS.", "Experience with Kubernetes."],
    benefits: ["Premium health care", "Laptop allowance"],
    company: { name: "ZaloPay", address: "District 7, HCMC", bio: "Fintech innovator." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-15",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_016",
    title: "Customer Success Manager",
    category: "Sales",
    department: "Sales",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 12000000, max: 18000000, currency: "VND" },
    location: "Da Nang",
    postedAt: "4 days ago",
    skills: ["Communication", "CRM", "Problem Solving"],
    description: ["Ensure customer satisfaction.", "Handle client inquiries."],
    requirements: ["Excellent interpersonal skills.", "Proficiency in CRM software."],
    benefits: ["Commission scheme", "Team building"],
    company: { name: "Shopee", address: "Hai Chau, Da Nang", bio: "E-commerce leader." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-20",
    createdBy: "company2",
    status: "approved",
  },
  {
    id: "job_017",
    title: "Frontend Developer (React)",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: true,
    logo: "https://via.placeholder.com/150",
    salary: { min: 18000000, max: 28000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "5 days ago",
    skills: ["React", "TypeScript", "Redux"],
    description: ["Build responsive web apps.", "Optimize site performance."],
    requirements: ["Deep React knowledge.", "Strong CSS skills."],
    benefits: ["13th month salary", "Flexible work"],
    company: { name: "Tiki", address: "District 1, HCMC", bio: "Trusted e-commerce." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-25",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_018",
    title: "Senior Accountant",
    category: "Finance",
    department: "Accounting",
    jobType: "Full-time",
    experienceLevel: "4+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 15000000, max: 22000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "6 days ago",
    skills: ["Taxation", "Auditing", "Excel"],
    description: ["Prepare financial statements.", "Manage tax reporting."],
    requirements: ["Strong accounting background.", "Certification (CPA) is a plus."],
    benefits: ["Insurance", "Annual leave"],
    company: { name: "Viettel", address: "Ba Dinh, Ha Noi", bio: "Leading Telco." },
    workingHours: "Mon - Fri",
    deadline: "2026-07-01",
    createdBy: "company2",
    status: "approved",
  },
  {
    id: "job_019",
    title: "Graphic Designer",
    category: "Design",
    department: "Marketing",
    jobType: "Contract",
    experienceLevel: "1+ year",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 10000000, max: 15000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "1 week ago",
    skills: ["Photoshop", "Illustrator", "Brand Design"],
    description: ["Create visual assets.", "Design marketing collateral."],
    requirements: ["Strong portfolio.", "Creative mindset."],
    benefits: ["Flexible remote work", "Creative projects"],
    company: { name: "PNJ", address: "Phu Nhuan, HCMC", bio: "Jewelry retail." },
    workingHours: "Flexible",
    deadline: "2026-06-15",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_020",
    title: "Data Scientist",
    category: "Data",
    department: "Data Science",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 35000000, max: 55000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Machine Learning", "Python", "TensorFlow"],
    description: ["Develop AI models.", "Conduct predictive analysis."],
    requirements: ["Advanced degree in CS/Math.", "Experience with ML ops."],
    benefits: ["Research budget", "Conference support"],
    company: { name: "VNG", address: "District 7, HCMC", bio: "Leading Tech company." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-30",
    createdBy: "company1",
    status: "approved",
  },
  {
    id: "job_021",
    title: "System Admin",
    category: "IT",
    department: "IT",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 14000000, max: 20000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "3 days ago",
    skills: ["Linux", "Windows Server", "Networking"],
    description: ["Maintain office networks.", "Provide technical support."],
    requirements: ["Experience with Linux.", "Troubleshooting skills."],
    benefits: ["Meal allowance", "Health package"],
    company: { name: "CMC", address: "Cau Giay, Ha Noi", bio: "ICT services." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-10",
    createdBy: "company2",
    status: "approved",
  },
  {
    id: "job_022",
    title: "Legal Executive",
    category: "Legal",
    department: "Legal",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 15000000, max: 25000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "4 days ago",
    skills: ["Contract Law", "Legal Research", "Compliance"],
    description: ["Review contracts.", "Advise on regulatory compliance."],
    requirements: ["Law degree.", "Detail oriented."],
    benefits: ["Training support", "Parking allowance"],
    company: { name: "Techcombank", address: "District 1, HCMC", bio: "Banking leader." },
    workingHours: "Mon - Fri",
    deadline: "2026-07-05",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_023",
    title: "SEO Specialist",
    category: "Marketing",
    department: "Marketing",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 12000000, max: 20000000, currency: "VND" },
    location: "Remote",
    postedAt: "1 week ago",
    skills: ["SEO", "Google Analytics", "Keyword Research"],
    description: ["Optimize web content.", "Execute link building."],
    requirements: ["Proven SEO track record.", "Analytical skills."],
    benefits: ["Remote work", "Performance bonuses"],
    company: { name: "TopCV", address: "Online", bio: "HR Tech." },
    workingHours: "Flexible",
    deadline: "2026-06-20",
    createdBy: "company2",
    status: "approved",
  },
  {
    id: "job_024",
    title: "Java Developer",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 20000000, max: 35000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "2 days ago",
    skills: ["Java", "Spring Boot", "Microservices"],
    description: ["Develop backend applications.", "Optimize performance."],
    requirements: ["Java expert.", "Experience with Spring."],
    benefits: ["Global project", "MacBook provided"],
    company: { name: "FPT Software", address: "District 9, HCMC", bio: "Global Tech." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-25",
    createdBy: "company1",
    status: "approved",
  },
  {
    id: "job_025",
    title: "HR Business Partner",
    category: "Human Resources",
    department: "HR",
    jobType: "Full-time",
    experienceLevel: "5+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 30000000, max: 50000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "1 day ago",
    skills: ["Strategy", "Talent Management", "Conflict Resolution"],
    description: ["Align HR strategy with business.", "Talent coaching."],
    requirements: ["Deep HR knowledge.", "Strategic mindset."],
    benefits: ["Executive bonus", "Insurance"],
    company: { name: "Viettel", address: "Cau Giay, Ha Noi", bio: "Global Telco." },
    workingHours: "Mon - Fri",
    deadline: "2026-07-10",
    createdBy: "company2",
    status: "approved",
  },
  {
    id: "job_026",
    title: "QA Automation Engineer",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 22000000, max: 32000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "5 days ago",
    skills: ["Selenium", "Java", "TestNG", "Jenkins"],
    description: ["Build automation frameworks.", "Maintain test suites."],
    requirements: ["Strong automation experience.", "Coding skills."],
    benefits: ["Learning budget", "Team events"],
    company: { name: "MoMo", address: "District 1, HCMC", bio: "Mobile payment." },
    workingHours: "Mon - Fri",
    deadline: "2026-06-30",
    createdBy: "company1",
    status: "pending",
  },
  {
    id: "job_027",
    title: "Internal Auditor",
    category: "Finance",
    department: "Finance",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 18000000, max: 28000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "6 days ago",
    skills: ["Auditing", "Risk Management", "Compliance"],
    description: ["Perform internal audits.", "Assess control risks."],
    requirements: ["Degree in Finance.", "Auditing skills."],
    benefits: ["Yearly review", "Allowance"],
    company: { name: "Vinamilk", address: "District 1, HCMC", bio: "Dairy giant." },
    workingHours: "Mon - Fri",
    deadline: "2026-07-05",
    createdBy: "company2",
    status: "rejected",
  },
  {
    id: "job_028",
    title: "Market Research Specialist",
    category: "Marketing",
    department: "Marketing",
    jobType: "Full-time",
    experienceLevel: "2+ years",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 14000000, max: 22000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "1 week ago",
    skills: ["Market Analysis", "Survey Design", "Data Viz"],
    description: ["Analyze market trends.", "Report competitor activity."],
    requirements: ["Analytical skills.", "Statistics knowledge."],
    benefits: ["Remote flexibility", "Bonus"],
    company: { name: "Shopee", address: "Cau Giay, Ha Noi", bio: "E-commerce." },
    workingHours: "Mon - Fri",
    deadline: "2026-07-15",
    createdBy: "company1",
    status: "approved",
  },
  {
    id: "job_029",
    title: "Fullstack Developer",
    category: "Software Development",
    department: "Engineering",
    jobType: "Full-time",
    experienceLevel: "3+ years",
    isBookmarked: true,
    logo: "https://via.placeholder.com/150",
    salary: { min: 25000000, max: 40000000, currency: "VND" },
    location: "Ho Chi Minh City",
    postedAt: "1 day ago",
    skills: ["React", "Node.js", "PostgreSQL"],
    description: ["End-to-end development.", "Feature deployment."],
    requirements: ["Fullstack expertise.", "Team player."],
    benefits: ["Stock options", "Health care"],
    company: { name: "Grab", address: "District 7, HCMC", bio: "Superapp." },
    workingHours: "Mon - Fri",
    deadline: "2026-07-20",
    createdBy: "company1",
    status: "approved",
  },
  {
    id: "job_030",
    title: "Junior IT Support",
    category: "IT",
    department: "IT",
    jobType: "Full-time",
    experienceLevel: "Entry level",
    isBookmarked: false,
    logo: "https://via.placeholder.com/150",
    salary: { min: 8000000, max: 12000000, currency: "VND" },
    location: "Ha Noi",
    postedAt: "3 days ago",
    skills: ["Hardware", "Windows", "Office Support"],
    description: ["Handle IT helpdesk.", "Maintain office hardware."],
    requirements: ["Basic IT skills.", "Service mindset."],
    benefits: ["Training provided", "Free snacks"],
    company: { name: "CMC", address: "Cau Giay, Ha Noi", bio: "ICT service." },
    workingHours: "Mon - Fri",
    deadline: "2026-07-25",
    createdBy: "company2",
    status: "approved",
  },

];