import type { Application } from "./types/application.types";

export const mockData: Application[] = [
  {
    id: 1,
    candidateName: "Nguyen Van A",
    jobTitle: "Frontend Developer",
    cvUrl:
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status: "PENDING",
    recruitment: {
      firstName: "Nguyễn",
      lastName: "Tuấn",
      gender: "male",
      dob: "01/01/2005",
      email: "user1@gmail.com",
      phone: "0800000001",
      address: "Thủ Đức, TP.HCM",
      taxId: "987654321",
      citizenId: "012345678",
      releaseDate: "10/01/2022",
      social: "facebook.com/tuan",
      bankAccount: "ACB - 654321",
      selfIntro: "Frontend Developer",
      jobTitle: "Frontend Developer",
      salary: "1200$",
      startDate: "01/06/2026",
    },
  },
  {
    id: 2,
    candidateName: "Tran Thi B",
    jobTitle: "Backend Developer",
    cvUrl:
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    status: "REVIEWING",
    recruitment: {
      firstName: "Trần",
      lastName: "B",
      gender: "female",
      dob: "12/03/2002",
      email: "user2@gmail.com",
      phone: "0800000002",
      address: "Quận 7, TP.HCM",
      taxId: "123456789",
      citizenId: "987654321",
      releaseDate: "15/02/2021",
      social: "linkedin.com/in/thib",
      bankAccount: "Vietcombank - 112233",
      selfIntro: "Backend Engineer",
      jobTitle: "Backend Developer",
      salary: "1500$",
      startDate: "15/06/2026",
    },
  },
];