server.port=8081

spring.datasource.url=jdbc:sqlserver://DESKTOP-RM7VAFI:61506;databaseName=KHOA;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

jwt.secret=mySuperSecretKeyForJwtToken12345678901234567890
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
